/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/CN.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CN(props) {
  const { nodes, materials } = useGLTF('/CN.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['SVGMat.004_CARTOON_NETWORK_logo.']} />
        <mesh geometry={nodes.Object_0.geometry} material={materials['Material.001_CNXD_logo_ND_texture.']} />
        <mesh geometry={nodes.Object_0_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_1.geometry} material={materials['Material_CNXD_logo_CX_texture.']} />
        <mesh geometry={nodes.Object_1_1.geometry} material={materials['Material.001']} />
      </group>
      <mesh geometry={nodes.geometry_0.geometry} material={materials.Material_0} position={[-0.749, -1.265, 1.024]} rotation={[0.391, 0.311, 0.03]} scale={0.194} />
    </group>
  )
}

useGLTF.preload('/CN.glb')
